// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqA4gu36gReZrgmC525Wmyod2qiA5kc0w',
    appId: '1:273596266688:web:c9165a19f817faf1151525',
    messagingSenderId: '273596266688',
    projectId: 'carpool-app-2f85d',
    authDomain: 'carpool-app-2f85d.firebaseapp.com',
    databaseURL: 'https://carpool-app-2f85d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carpool-app-2f85d.appspot.com',
    measurementId: 'G-NVR87T83X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnL0UnGELmWTsHCqKNKasb-8_xJZgmnE',
    appId: '1:273596266688:android:568602e5ec1ab8de151525',
    messagingSenderId: '273596266688',
    projectId: 'carpool-app-2f85d',
    databaseURL: 'https://carpool-app-2f85d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carpool-app-2f85d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Y5sEHuh7icYMjnAM-odyDcFfHnygMpk',
    appId: '1:273596266688:ios:3497c4a34ed2dc5f151525',
    messagingSenderId: '273596266688',
    projectId: 'carpool-app-2f85d',
    databaseURL: 'https://carpool-app-2f85d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carpool-app-2f85d.appspot.com',
    iosClientId: '273596266688-opa7e99kcrq7biog1gpbs8tah5pda8c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cp301',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Y5sEHuh7icYMjnAM-odyDcFfHnygMpk',
    appId: '1:273596266688:ios:3497c4a34ed2dc5f151525',
    messagingSenderId: '273596266688',
    projectId: 'carpool-app-2f85d',
    databaseURL: 'https://carpool-app-2f85d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carpool-app-2f85d.appspot.com',
    iosClientId: '273596266688-opa7e99kcrq7biog1gpbs8tah5pda8c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cp301',
  );
}
